// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAlbums() {
  return window['go']['main']['App']['GetAlbums']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function InitDb() {
  return window['go']['main']['App']['InitDb']();
}

export function RemoveAlbumsFromDevice(arg1) {
  return window['go']['main']['App']['RemoveAlbumsFromDevice'](arg1);
}

export function ScanDevice() {
  return window['go']['main']['App']['ScanDevice']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SetConfig(arg1) {
  return window['go']['main']['App']['SetConfig'](arg1);
}

export function SyncDevice(arg1) {
  return window['go']['main']['App']['SyncDevice'](arg1);
}

export function SyncMusicCollection() {
  return window['go']['main']['App']['SyncMusicCollection']();
}

export function TransferAlbum(arg1) {
  return window['go']['main']['App']['TransferAlbum'](arg1);
}
