// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAlbums():Promise<Array<main.Album>>;

export function GetConfig():Promise<main.Config>;

export function InitDb():Promise<void>;

export function SelectDirectory():Promise<string>;

export function SetConfig(arg1:main.Config):Promise<void>;

export function SyncDevice():Promise<void>;

export function SyncMusicCollection():Promise<void>;
