// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function InitDb() {
  return window['go']['main']['App']['InitDb']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SetConfig(arg1) {
  return window['go']['main']['App']['SetConfig'](arg1);
}
